server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  instance:
    hostname: localhost                   #\uC708\uB3C4\uC6B0 \uACBD\uC6B0 \uD544\uC694
  client:
    register-with-eureka: false
    fetch-registry: false